# Generated by Django 5.0.7 on 2024-07-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=255, null=True)),
                ("calories_amount", models.PositiveIntegerField(null=True)),
                ("serving", models.PositiveIntegerField(null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Dessert", "Dessert"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                            ("Breakfast", "Breakfast"),
                            ("Fruit", "Fruit"),
                            ("Appetizer", "Appetizer"),
                            ("Drink", "Drink"),
                            ("Juice", "Juice"),
                            ("Coffee", "Coffee"),
                            ("Milk", "Milk"),
                            ("Tea", "Tea"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
