# Generated by Django 5.0.7 on 2024-07-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calories",
            name="category",
            field=models.CharField(
                choices=[
                    ("Dessert", "Dessert"),
                    ("Lunch", "Lunch"),
                    ("Dinner", "Dinner"),
                    ("Breakfast", "Breakfast"),
                    ("Fruit", "Fruit"),
                    ("Appetizer", "Appetizer"),
                    ("Drink", "Drink"),
                    ("Juice", "Juice"),
                    ("Coffee", "Coffee"),
                    ("Milk", "Milk"),
                    ("Tea", "Tea"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="calories",
            name="food_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
