# Generated by Django 5.0.7 on 2024-07-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_calories_date_calories_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calories",
            options={"verbose_name_plural": "Calories"},
        ),
    ]
